print("+--------------------+")
print("|   Hello Stefano!   |")
print("+--------------------+")
print("         \\")
print("           \\     ^__^")
print("                ( oo )\\________")
print("                ( __ )\\        )/\\/")
print("                      ||------w |")
print("                      ||       ||")
